In [130]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.linear_model import LinearRegression, SGDRegressor
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [131]:
data = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/housing_data_08-02-2021.csv')

In [132]:
data

location           district   
0     город Ташкент, Юнусабадский район, Юнусабад 8-...       Юнусабадский  \
1     город Ташкент, Яккасарайский район, 1-й тупик ...      Яккасарайский   
2     город Ташкент, Чиланзарский район, Чиланзар 2-...       Чиланзарский   
3     город Ташкент, Чиланзарский район, Чиланзар 9-...       Чиланзарский   
4     город Ташкент, Чиланзарский район, площадь Актепа       Чиланзарский   
...                                                 ...                ...   
7560  город Ташкент, Яшнободский район, Городок Авиа...        Яшнободский   
7561  город Ташкент, Яшнободский район, 1-й проезд А...        Яшнободский   
7562  город Ташкент, Шайхантахурский район, Зульфиях...    Шайхантахурский   
7563  город Ташкент, Мирзо-Улугбекский район, Буюк И...  Мирзо-Улугбекский   
7564  город Ташкент, Чиланзарский район, Чиланзар 6-...       Чиланзарский   

      rooms size  level  max_levels  price  
0         3   57      4           4  52000  
1         2   52      4           5  56000  
2         2   42      4           4  37000  
3         3   65      1           4  49500  
4         3   70      3           5  55000  
...     ...  ...    ...         ...    ...  
7560      1   38      5           5  24500  
7561      2   49      1           4  32000  
7562      2   64      3           9  40000  
7563      1   18      1           4  11000  
7564      1   30      2           4  22914  

[7565 rows x 7 columns]

In [133]:
data['district'].value_counts()

district
Чиланзарский         1641
Мирзо-Улугбекский    1382
Юнусабадский          883
Учтепинский           880
Мирабадский           773
Яккасарайский         658
Яшнободский           484
Шайхантахурский       396
Олмазорский           269
Сергелийский          175
Янгихаётский           16
Бектемирский            8
Name: count, dtype: int64

In [134]:
label_district = {
    'Чиланзарский'       : 0 ,
    'Мирзо-Улугбекский'  : 1,
    'Юнусабадский'       : 2,
    'Учтепинский'        : 2,
    'Мирабадский'        : 3,   
    'Яккасарайский'      : 3,
    'Яшнободский'        : 4,
    'Шайхантахурский'    : 4,
    'Олмазорский'        : 4,
    'Сергелийский'       : 4,
    'Янгихаётский'       : 4,
    'Бектемирский'       : 4 
}

In [135]:
region = data['district'].to_numpy()
region

array(['Юнусабадский', 'Яккасарайский', 'Чиланзарский', ...,
       'Шайхантахурский', 'Мирзо-Улугбекский', 'Чиланзарский'],
      dtype=object)

In [136]:
for i in range(len(region)):

    region[i] = label_district[region[i]]
region

array([2, 3, 0, ..., 4, 1, 0], dtype=object)

In [137]:
data['district'] = region
data

location district  rooms size   
0     город Ташкент, Юнусабадский район, Юнусабад 8-...        2      3   57  \
1     город Ташкент, Яккасарайский район, 1-й тупик ...        3      2   52   
2     город Ташкент, Чиланзарский район, Чиланзар 2-...        0      2   42   
3     город Ташкент, Чиланзарский район, Чиланзар 9-...        0      3   65   
4     город Ташкент, Чиланзарский район, площадь Актепа        0      3   70   
...                                                 ...      ...    ...  ...   
7560  город Ташкент, Яшнободский район, Городок Авиа...        4      1   38   
7561  город Ташкент, Яшнободский район, 1-й проезд А...        4      2   49   
7562  город Ташкент, Шайхантахурский район, Зульфиях...        4      2   64   
7563  город Ташкент, Мирзо-Улугбекский район, Буюк И...        1      1   18   
7564  город Ташкент, Чиланзарский район, Чиланзар 6-...        0      1   30   

      level  max_levels  price  
0         4           4  52000  
1         4           5  56000  
2         4           4  37000  
3         1           4  49500  
4         3           5  55000  
...     ...         ...    ...  
7560      5           5  24500  
7561      1           4  32000  
7562      3           9  40000  
7563      1           4  11000  
7564      2           4  22914  

[7565 rows x 7 columns]

In [138]:
data = data[data['size'] != 'Площадьземли:1сот']
data

location district  rooms size   
0     город Ташкент, Юнусабадский район, Юнусабад 8-...        2      3   57  \
1     город Ташкент, Яккасарайский район, 1-й тупик ...        3      2   52   
2     город Ташкент, Чиланзарский район, Чиланзар 2-...        0      2   42   
3     город Ташкент, Чиланзарский район, Чиланзар 9-...        0      3   65   
4     город Ташкент, Чиланзарский район, площадь Актепа        0      3   70   
...                                                 ...      ...    ...  ...   
7560  город Ташкент, Яшнободский район, Городок Авиа...        4      1   38   
7561  город Ташкент, Яшнободский район, 1-й проезд А...        4      2   49   
7562  город Ташкент, Шайхантахурский район, Зульфиях...        4      2   64   
7563  город Ташкент, Мирзо-Улугбекский район, Буюк И...        1      1   18   
7564  город Ташкент, Чиланзарский район, Чиланзар 6-...        0      1   30   

      level  max_levels  price  
0         4           4  52000  
1         4           5  56000  
2         4           4  37000  
3         1           4  49500  
4         3           5  55000  
...     ...         ...    ...  
7560      5           5  24500  
7561      1           4  32000  
7562      3           9  40000  
7563      1           4  11000  
7564      2           4  22914  

[7564 rows x 7 columns]

In [139]:
data = data[data['price'] != 'Договорная']
data

location district  rooms size   
0     город Ташкент, Юнусабадский район, Юнусабад 8-...        2      3   57  \
1     город Ташкент, Яккасарайский район, 1-й тупик ...        3      2   52   
2     город Ташкент, Чиланзарский район, Чиланзар 2-...        0      2   42   
3     город Ташкент, Чиланзарский район, Чиланзар 9-...        0      3   65   
4     город Ташкент, Чиланзарский район, площадь Актепа        0      3   70   
...                                                 ...      ...    ...  ...   
7560  город Ташкент, Яшнободский район, Городок Авиа...        4      1   38   
7561  город Ташкент, Яшнободский район, 1-й проезд А...        4      2   49   
7562  город Ташкент, Шайхантахурский район, Зульфиях...        4      2   64   
7563  город Ташкент, Мирзо-Улугбекский район, Буюк И...        1      1   18   
7564  город Ташкент, Чиланзарский район, Чиланзар 6-...        0      1   30   

      level  max_levels  price  
0         4           4  52000  
1         4           5  56000  
2         4           4  37000  
3         1           4  49500  
4         3           5  55000  
...     ...         ...    ...  
7560      5           5  24500  
7561      1           4  32000  
7562      3           9  40000  
7563      1           4  11000  
7564      2           4  22914  

[7465 rows x 7 columns]

In [178]:
X = data.drop(['price', 'location'], axis=1).to_numpy().astype(np.float32)
X

array([[ 2.,  3., 57.,  4.,  4.],
       [ 3.,  2., 52.,  4.,  5.],
       [ 0.,  2., 42.,  4.,  4.],
       ...,
       [ 4.,  2., 64.,  3.,  9.],
       [ 1.,  1., 18.,  1.,  4.],
       [ 0.,  1., 30.,  2.,  4.]], dtype=float32)

In [179]:
Y = data['price'].to_numpy().astype(np.float32).reshape(-1,1)
Y

array([[52000.],
       [56000.],
       [37000.],
       ...,
       [40000.],
       [11000.],
       [22914.]], dtype=float32)

In [154]:
len(Y)

7465

In [155]:
len(X)

7465

In [156]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=1)

# Linear Regression model

In [157]:
linear_model = LinearRegression()

In [158]:
linear_model.fit(X_train, y_train)

LinearRegression()

In [159]:
def metrcis(y_true, y_pred):
    r2 = r2_score(y_true, y_pred)
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    print(f"r2 score : {r2}\nMAE : {mae}\nMSE : {mse}")

In [162]:
y_pred = linear_model.predict(X_test)

In [163]:
metrcis(y_test, y_pred)

r2 score : 0.0011978457879237014
MAE : 60817.22132246816
MSE : 1825706911003.0874


In [164]:
y_pred = linear_model.predict(X_train)

In [165]:
metrcis(y_train, y_pred)

r2 score : 0.014362189843396433
MAE : 29156.73854249566
MSE : 54862878260.858444


# SGD model

In [167]:
sgd_model = SGDRegressor()

In [172]:
sgd_model.fit(X_train, y_train)

/home/ai/Projects/AI/ai_full/lib/python3.11/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SGDRegressor()

In [170]:
y_pred = sgd_model.predict(X_test)

In [171]:
metrcis(y_test, y_pred)

r2 score : -90591738843205.48
MAE : 683511734517.0596
MSE : 1.6559231774615367e+26
